# 공통 변수
db_host: 192.0.2.21       # db1 직접 접속 주소
db_lb_host: 192.0.2.32    # lbdb1 로드밸런서 주소
db_name: tododb
db_table: web_tab
db_port: 5432

# NFS
nfs_host: 192.0.2.41      # nfs1 주소

# iSCSI
iscsi_host: 192.0.2.51    # iscsi1 주소

# DNS
dns_host: 192.0.2.61      # dns1 주소

# 민감 정보는 group_vars/all/vault.yml 에서 관리
db_user: "{{ vault_db_user }}"
db_password: "{{ vault_db_password }}"
