---
- name: Step 6 - Keep step 5 base
  import_playbook: step5_add_nfs.yml

- name: Step 6 - Add iSCSI target
  hosts: iscsi_target
  become: true
  roles:
    - iscsi_target

- name: Step 6 - Configure iSCSI initiators on DB servers
  hosts: db
  become: true
  vars:
    iscsi_target_ip: "{{ hostvars[groups['iscsi_target'][0]].ansible_host | default(groups['iscsi_target'][0]) }}"
  roles:
    - iscsi_initiator

