---
- name: Step 3 - Prepare two DB servers
  hosts: db
  become: true
  roles:
    - db

- name: Step 3 - Add DB load balancer (HAProxy TCP)
  hosts: lb_db
  become: true
  vars:
    lb_mode: tcp
    frontend_port: 3306
    backend_group: db
    backend_port: 3306
  roles:
    - lb

