---
app_name: todoapp

db_name: todoapp
db_user: todo
literal:db_password: REDACTED
db_port: 3306

web_http_port: 80
db_endpoint: "{{ hostvars[groups['db'][0]].ansible_host | default(groups['db'][0]) }}"

lb_balance_algo: roundrobin

nfs_export_dir: /srv/nfs/webroot
nfs_mount_dir: /var/www/html
nfs_clients_cidr: 10.0.10.0/24

iscsi_iqn: iqn.2026-02.com.sesac:todo.mysql
iscsi_backing_file: /var/lib/iscsi-disks/mysql-data.img
iscsi_backing_size_mb: 2048
iscsi_target_portal: "{{ hostvars[groups['iscsi_target'][0]].ansible_host | default(groups['iscsi_target'][0]) }}"
iscsi_enable_mount: false

dns_zone_name: sesac.cloud.com
dns_app_record: app
dns_db_record: db

